import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import {
  assembleGeminiExtension,
  copySkillTree,
  assertNoSourceSymlinks,
  validateGeminiDestination
} from '../scripts/build-gemini-extension.mjs';

test('assembles a Gemini-native extension outside the portable package', () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), 'fulcrum-gemini-'));
  const destination = path.join(parent, 'fulcrum-ai-toolkit-gemini');

  try {
    assembleGeminiExtension(destination);
    const manifest = JSON.parse(
      fs.readFileSync(path.join(destination, 'gemini-extension.json'), 'utf8')
    );
    const skillNames = fs.readdirSync(path.join(destination, 'skills')).sort();

    assert.equal(manifest.name, 'fulcrum-ai-toolkit-gemini');
    assert.equal(manifest.name, path.basename(destination));
    assert.equal(manifest.version, '0.1.2');
    assert.equal(
      fs.readFileSync(path.join(destination, '.fulcrum-ai-toolkit-gemini-generated'), 'utf8'),
      'fulcrum-ai-toolkit-gemini\n'
    );
    assert.deepEqual(skillNames, [
      'fulcrum-access-management',
      'fulcrum-app-builder',
      'fulcrum-app-design',
      'fulcrum-app-extensions',
      'fulcrum-app-goal',
      'fulcrum-app-scorecard',
      'fulcrum-data-events',
      'fulcrum-data-migration',
      'fulcrum-discovery',
      'fulcrum-gis-mapping',
      'fulcrum-integration-patterns',
      'fulcrum-performance-review',
      'fulcrum-product-knowledge',
      'fulcrum-query-api',
      'fulcrum-report-building',
      'fulcrum-safety',
      'fulcrum-solution-document',
      'fulcrum-workflow-decomposition'
    ]);
    assert.equal(fs.existsSync(path.join(destination, 'plugin.json')), false);
    assert.equal(fs.existsSync(path.join(destination, 'mcp.json')), false);
  } finally {
    fs.rmSync(parent, { recursive: true, force: true });
  }
});

test('refuses to delete an unrelated non-empty destination', () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), 'fulcrum-gemini-owned-'));
  const destination = path.join(parent, 'fulcrum-ai-toolkit-gemini');
  const sentinel = path.join(destination, 'keep-me.txt');

  try {
    fs.mkdirSync(destination, { recursive: true });
    fs.writeFileSync(sentinel, 'do not delete');

    assert.throws(
      () => assembleGeminiExtension(destination),
      /must be empty or contain the assembler marker/
    );
    assert.equal(fs.readFileSync(sentinel, 'utf8'), 'do not delete');
  } finally {
    fs.rmSync(parent, { recursive: true, force: true });
  }
});

test('replaces a destination previously generated by the assembler', () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), 'fulcrum-gemini-replace-'));
  const destination = path.join(parent, 'fulcrum-ai-toolkit-gemini');
  const staleFile = path.join(destination, 'stale.txt');

  try {
    assembleGeminiExtension(destination);
    fs.writeFileSync(staleFile, 'stale');
    assembleGeminiExtension(destination);

    assert.equal(fs.existsSync(staleFile), false);
    assert.equal(
      fs.readFileSync(path.join(destination, '.fulcrum-ai-toolkit-gemini-generated'), 'utf8'),
      'fulcrum-ai-toolkit-gemini\n'
    );
  } finally {
    fs.rmSync(parent, { recursive: true, force: true });
  }
});

test('does not treat a matching manifest as destination ownership', () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), 'fulcrum-gemini-manifest-'));
  const destination = path.join(parent, 'fulcrum-ai-toolkit-gemini');

  try {
    fs.mkdirSync(destination, { recursive: true });
    fs.copyFileSync(
      path.join(
        path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'),
        'adapters',
        'gemini',
        'gemini-extension.json'
      ),
      path.join(destination, 'gemini-extension.json')
    );
    fs.writeFileSync(path.join(destination, 'customized.txt'), 'customized');

    assert.throws(
      () => assembleGeminiExtension(destination),
      /must be empty or contain the assembler marker/
    );
    assert.equal(fs.existsSync(path.join(destination, 'customized.txt')), true);
  } finally {
    fs.rmSync(parent, { recursive: true, force: true });
  }
});

test('rejects symlinks in the Gemini source tree before copying', () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), 'fulcrum-gemini-source-'));
  const source = path.join(parent, 'skills');
  const destination = path.join(parent, 'output');
  const externalFile = path.join(parent, 'external.txt');

  try {
    fs.mkdirSync(source, { recursive: true });
    fs.writeFileSync(externalFile, 'external');
    fs.symlinkSync(externalFile, path.join(source, 'external.txt'));

    assert.throws(
      () => assertNoSourceSymlinks(source),
      /Gemini source tree must not contain symbolic links/
    );
    assert.throws(
      () => copySkillTree(source, destination),
      /Gemini source tree must not contain symbolic links/
    );
    assert.equal(fs.existsSync(destination), false);
  } finally {
    fs.rmSync(parent, { recursive: true, force: true });
  }
});

test('rejects dangerous or source-tree Gemini destinations before deletion', () => {
  const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const portablePackage = path.join(repositoryRoot, 'plugins', 'fulcrum-ai-toolkit');
  const filesystemRoot = path.parse(repositoryRoot).root;
  const dangerousDestinations = [
    filesystemRoot,
    path.dirname(repositoryRoot),
    repositoryRoot,
    portablePackage,
    path.join(repositoryRoot, 'adapters', 'gemini')
  ];

  for (const destination of dangerousDestinations) {
    assert.throws(() => validateGeminiDestination(destination), /destination must not|destinations inside/);
  }

  const parent = fs.mkdtempSync(path.join(os.tmpdir(), 'fulcrum-gemini-link-'));
  try {
    const repositoryLink = path.join(parent, 'repository-link');
    fs.symlinkSync(repositoryRoot, repositoryLink, 'dir');
    assert.throws(
      () => validateGeminiDestination(path.join(repositoryLink, 'plugins', 'fulcrum-ai-toolkit')),
      /destination must not|destinations inside/
    );

    const externalTarget = path.join(parent, 'external-target');
    const externalLink = path.join(parent, 'external-link');
    fs.mkdirSync(externalTarget);
    fs.symlinkSync(externalTarget, externalLink, 'dir');
    assert.throws(
      () => validateGeminiDestination(externalLink),
      /destination must not be an existing symbolic link/
    );

    const sourceTreeLink = path.join(repositoryRoot, 'plugins', '.gemini-review-link');
    fs.symlinkSync(externalTarget, sourceTreeLink, 'dir');
    try {
      assert.throws(
        () => validateGeminiDestination(path.join(sourceTreeLink, 'generated')),
        /destinations inside the repository/
      );
    } finally {
      fs.unlinkSync(sourceTreeLink);
    }
  } finally {
    fs.rmSync(parent, { recursive: true, force: true });
  }
});
