server {
    listen 9000;
    server_name *.chaos.fulcrum.tools;
    access_log /tmp/nginx_cogclient.access.log;
    error_log /tmp/nginx_cogclient.error.log;
    root /www/data;

    location /docs {
        root /www/data;
        index index.htm index.html;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}